mysite/adminapp/urls.py
from django.urls import path
from . import views

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', views.user_create, name='user_create'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/update/<int:pk>/', views.user_update, name='user_update'),
    path('users/delete/<int:pk>/', views.user_delete, name='user_delete'),

    path('categories/create/', views.category_create, name='category_create'),
    path('categories/', views.categories, name='category_list'),
    path('categories/update/<int:pk>/', views.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', views.category_delete, name='category_delete'),

    path('products/create/<int:pk>/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', views.ProductListView.as_view(), name='product_list'),
    path('products/update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('products/detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('mainapp.urls')),
    path('', include('authapp.urls')),
    path('basket/', include('basketapp.urls')),
    path('control/', include('adminapp.urls')),
    path('order/', include('orderapp.urls')),

    path('', include('social_django.urls', namespace='social'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mysite/adminapp/models.py
from django.db import models

# Create your models here.

mysite/adminapp/forms.py
from django import forms

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm:
    pass


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['is_active', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if hasattr(field.widget, 'input_type') and field.widget.input_type == 'checkbox':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(ProductCreateForm):
    class Meta(ProductCreateForm.Meta):
        exclude = ['', ]

mysite/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.db.models import F
from django.db import connection

from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from .forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm, ProductCreateForm
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from mainapp.models import ProductCategory, Product


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)


class AccessMixin:

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


# Create your views here.
@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)

        if user_form.is_valid():
            user_form.save()
            return redirect('adminapp:user_list')
    else:
        user_form = ShopUserRegisterForm()

    context = {
        'form': user_form,
    }
    return render(request, 'adminapp/user_form.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     context = {
#         'object_list': ShopUser.objects.all().order_by('-is_active')
#     }
#     return render(request, 'adminapp/users.html', context)


class UserListView(AccessMixin, ListView):
    template_name = 'adminapp/users.html'
    model = ShopUser
    ordering = '-is_active'



@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    current_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        user_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=current_user)

        if user_form.is_valid():
            user_form.save()
            return redirect('adminapp:user_list')
    else:
        user_form = ShopUserAdminEditForm(instance=current_user)

    context = {
        'form': user_form,
    }
    return render(request, 'adminapp/user_form.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    current_user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        current_user.is_active = False if current_user.is_active else True
        current_user.save()
        return redirect('adminapp:user_list')

    context = {
        'object': current_user,
    }
    return render(request, 'adminapp/user_delete.html', context)


@user_passes_test(lambda u: u.is_superuser)
def category_create(request):
    return None


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    context = {
        'object_list': ProductCategory.objects.all().order_by('-is_active')
    }
    return render(request, 'adminapp/categories.html', context)


#@user_passes_test(lambda u: u.is_superuser)
#def category_update(request):
#    return None

class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    template_name = 'adminapp/product_form.html'
    success_url = reverse_lazy('adminapp:category_list')

#   def get_success_url(self):
#       return reverse('adminapp:category_update', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data.get('discount')
            if discount:
                self.object.product_set.update(
                    price=F('price') * (1 - discount / 100.0)
                )
        return super().form_valid(form)

@user_passes_test(lambda u: u.is_superuser)
def category_delete(request):
    return None


# @user_passes_test(lambda u: u.is_superuser)
# def product_create(request):
#     return None

class ProductCreateView(AccessMixin, CreateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    form_class = ProductCreateForm

    #    success_url = reverse_lazy('adminapp:product_list')

    def get_success_url(self):
        return reverse('adminapp:product_list', args=[self.kwargs['pk']])


# @user_passes_test(lambda u: u.is_superuser)
# def product_update(request):
#     return None

class ProductUpdateView(AccessMixin, UpdateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    form_class = ProductEditForm

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])


# @user_passes_test(lambda u: u.is_superuser)
# def products(request, pk):
#     context = {
#         'object_list': Product.objects.filter(category__pk=pk).order_by('-is_active'),
#         'category': get_object_or_404(ProductCategory, pk=pk),
#     }
#     return render(request, 'adminapp/products.html', context)


class ProductListView(AccessMixin, ListView):
    model = Product
    template_name = 'adminapp/products.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['category'] = get_object_or_404(ProductCategory, pk=self.kwargs.get('pk'))
        return context_data

    def get_queryset(self):
        return Product.objects.filter(category__pk=self.kwargs.get('pk')).order_by('-is_active')


# @user_passes_test(lambda u: u.is_superuser)
# def product_delete(request):
#     return None


class ProductDeleteView(AccessMixin, DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])


# @user_passes_test(lambda u: u.is_superuser)
# def product_detail(request):
#     return None


class ProductDetailView(AccessMixin, DetailView):
    model = Product
    template_name = 'adminapp/product_detail.html'

mysite/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'mainapp/fonts/font-awesome/css/font-awesome.css' %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
  <div class="container">
    <div class="h2 text-center head">
      Админка
    </div>
    {% block menu %}
      <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
      </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

mysite/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="categories_list">
    <button class="new_category">
      <a href="{% url 'adminapp:category_create' %}">
        новая категория
      </a>
    </button>

    {% for object in object_list %}
      <div class="category_record {% if not object.is_active %}not_active{% endif %}">
        <div class="category_name">
          {{ object.name|title }}
        </div>
        <div class="category_actions">
          <button>
            <a href="{% url 'adminapp:product_list' object.pk %}">
              товары категории
            </a>
          </button>
          <button>
            <a href="{% url 'adminapp:category_update' object.pk %}">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'adminapp:category_delete' object.pk %}">
              {% if object.is_active %}
                удалить
              {% else %}
                восстановить
              {% endif %}
            </a>
          </button>
        </div>
        <div class="category_desc">
          {{ object.description|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

mysite/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="">
        {% if object.is_active %}
            Уверены, что хотите удалить категорию {{ object.name }}?
        {% else %}
            Уверены, что хотите восстановить категорию?
        {% endif %}
    </div>
    <form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Уверен">
    </form>
    <a href="{% url 'adminapp:category_list' %}" class="btn btn-success">Нет</a>
{% endblock %}

mysite/adminapp/templates/adminapp/category_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить" class="btn btn-primary col-lg-12">
    </form>
    <a href="{% url 'adminapp:category_list' %}" class="btn btn-warning col-lg-12">Назад</a>
    <script>
    window.onload = function() {

    var inputs = document.getElementsByTagName('input');

    for(var i = 0; i < inputs.length; i++) {
        if(inputs[i].type.toLowerCase() == 'checkbox') {
            inputs[i].classList.remove("form-control");
        }
    }
    };
    </script>
{% endblock %}

mysite/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="">
        {% if object.is_active %}
            Уверены, что хотите удалить продукт {{ object.name }}?
        {% else %}
            Уверены, что хотите восстановить продукт?
        {% endif %}
    </div>
    <form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Уверен">
    </form>
    <a href="{% url 'adminapp:product_list' object.category.pk %}" class="btn btn-success">Нет</a>
{% endblock %}

mysite/adminapp/templates/adminapp/product_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
    <div class="product_read">
        <div class="product_name">
            Продукт‚<strong>{{ object.category.name|title }} / {{ object.name|title }}</strong>
        </div>
        <img src="{{object.image|media_for_products}}" alt="{{ object.name }}">
        <div class="summary">
            <b>Цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href="{% url 'adminapp:product_update' object.pk %}">редактировать</a>
                </button>
            </p>
            <p>
                <button>
                    <a href="{% url 'adminapp:product_delete' object.pk %}">удалить</a>
                </button>
            </p>
            <p>
                <button>
                    <a href="{% url 'adminapp:product_list' object.category.pk %}">назад</a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>
                {{ object.short_desc }}
            </p>
            <br>
            <br>
            <b>подробная информация</b>
            <p>
                {{ object.description }}
            </p>
        </div>
    </div>
{% endblock %}

mysite/adminapp/templates/adminapp/product_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить" class="btn btn-primary col-lg-12">
    </form>
      <a href="{% url 'adminapp:category_list' %}" class="btn btn-warning col-lg-12">Назад</a>
    <script>

    </script>
{% endblock %}

mysite/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
  <div class="products_list">
    <button class="new_product">
      <a href="{% url 'adminapp:product_create' category.pk %}"> новый продукт </a>
    </button>

    {% for object in object_list %}
      <div class="product_record {% if not object.is_active %}not_active{% endif %}">
        <img
          src="{{object.image|media_for_products}}"
          alt="{{ object.name }}">
    <!-- /media/{{object.image|default:'products/default.jpg'}} -->
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href="{% url 'adminapp:product_detail' object.pk %}">
              подробнее
            </a>
          </button>
          <button>
            <a href="{% url 'adminapp:product_update' object.pk %}">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'adminapp:product_delete' object.pk %}">
              {% if object.is_active %}
                удалить
              {% else %}
                восстановить
              {% endif %}
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>

    {% endfor%}
  </div>
{% endblock %}

mysite/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="">
        {% if object.is_active %}
            Уверены, что хотите удалить пользователя {{ object.get_full_names }}?
        {% else %}
            Уверены, что хотите восстановить пользователя?
        {% endif %}
    </div>
    <form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Уверен">
    </form>
    <a href="{% url 'adminapp:user_list' %}" class="btn btn-success">Нет</a>
{% endblock %}

mysite/adminapp/templates/adminapp/user_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить" class="btn btn-primary col-lg-12">
    </form>
    <a href="{% url 'adminapp:user_list' %}" class="btn btn-warning col-lg-12">Назад</a>
{% endblock %}

mysite/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
  <div class="users_list">
    <button class="new_user">
      <a href="{% url 'adminapp:user_create' %}">
        новый пользователь
      </a>
    </button>
    {% for object in object_list %}
      <div 
       class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img
          src="{{ object.avatar|media_for_users }}"
          alt="{{ object.username }}">
        <div class="user_role">
          {% if object.is_superuser %}
            администратор
          {% else %}
            пользователь
          {% endif %}
          <button>
            <a href="{% url 'adminapp:user_update' object.pk %}">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'adminapp:user_delete' object.pk %}">
              {% if object.is_active %}
                удалить
              {% else %}
                восстановить
              {% endif %}
            </a>
          </button>
        </div>
        <div class="user_name">
          <p><strong>{{ object.username }}</strong></p>
	    <p>
            {% if object.first_name %}
              <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
                  <p>{{ object.last_name|title }}</p>
                {% endif %}
            {% endif %}
          </p>
        </div>
        <div class="user_age">
          age:<br>
          {{ object.age }} лет
        </div>
        <div class="user_email">
          email:<br>
          {{ object.email }}
        </div>
        <div class="user_lastlogin">
          logged:<br>
          {{ object.last_login }}
        </div>
      </div><br>
    {% endfor%}
  </div>
{% endblock %}