mysite/authapp/urls.py
from django.urls import path
from . import views

app_name = 'authapp'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('verify/<email>/<key>', views.verify, name='verify'),

]

mysite/mainapp/urls.py
from django.urls import path, include
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('products/', views.products, name='products'),
    path('category/<int:pk>/', views.ProductsListView.as_view(), name='category'),
    path('product/<int:pk>/', views.product, name='product'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('mainapp.urls')),
    path('', include('authapp.urls')),
    path('basket/', include('basketapp.urls')),
    path('control/', include('adminapp.urls')),
    path('order/', include('orderapp.urls')),

    path('', include('social_django.urls', namespace='social'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mysite/authapp/models.py
from django.conf import settings

from django.db import models
from django.contrib.auth.models import User, AbstractUser

import pytz
from datetime import datetime, timedelta


# Create your models here.
class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True, verbose_name='аватар', default='default.jpg')
    age = models.PositiveSmallIntegerField(verbose_name='возраст', null=True, default=18)

    activate_key = models.CharField(max_length=128, verbose_name='Ключ активации', blank=True, null=True)
    activate_key_expired = models.DateTimeField(blank=True, null=True)

    def is_activate_key_expired(self):
        return datetime.now(pytz.timezone(settings.TIME_ZONE)) > (self.activate_key_expired + timedelta(hours=48))

    def activate_user(self):
        self.is_active = True
        self.activate_key = None
        self.activate_key_expired = None
        self.save()


class ShopUserProfile(models.Model):
    MALE = 'М'
    FEMALE = 'W'
    OTHER = 'O'

    GENDERS = (
        (MALE, 'М'),
        (FEMALE, 'Ж'),
        (OTHER, 'И'),
    )

    user = models.OneToOneField(ShopUser, null=False, unique=True, on_delete=models.CASCADE, db_index=True)
    tagline = models.CharField(max_length=128, verbose_name='Тэги', blank=True)
    about_me = models.TextField(verbose_name='Обо мне')
    gender = models.CharField(choices=GENDERS, default=OTHER, verbose_name='Пол', max_length=1)

mysite/authapp/forms.py
import hashlib
from django.conf import settings

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from .models import ShopUser, ShopUserProfile
import pytz
from datetime import datetime, timedelta


class ValidAge:

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Слишком молод!')
        elif data > 100:
            raise forms.ValidationError('Слишком стар!')
        return data


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ShopUserRegisterForm(UserCreationForm, ValidAge):
    class Meta:
        model = ShopUser
        fields = ['username', 'avatar', 'email', 'age', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if hasattr(field.widget, 'input_type') and field.widget.input_type == 'checkbox':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def save(self, *args, **kwargs):
        user = super().save(*args, **kwargs)
        user.is_active = False
        user.activate_key = hashlib.sha1(user.email.encode('utf8')).hexdigest()

        user.activate_key_expired = datetime.now(pytz.timezone(settings.TIME_ZONE))
        user.save()

        print(user.activate_key)

        return user


class ShopUserEditForm(UserChangeForm, ValidAge):
    class Meta:
        model = ShopUser
        fields = ['username', 'first_name', 'last_name', 'avatar', 'email', 'age', 'password', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():

            if hasattr(field.widget, 'input_type') and field.widget.input_type == 'checkbox':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()
                field.help_text = ''


class ShopUserProfileEditForm(forms.ModelForm):
    class Meta:
        model = ShopUserProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if hasattr(field.widget, 'input_type') and field.widget.input_type == 'checkbox':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

mysite/authapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse
from .forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm, ShopUserProfileEditForm
from .models import ShopUser
from .services import send_verify_email


# Create your views here.
def login(request):
    login_form = ShopUserLoginForm(data=request.POST)

    next_param = request.GET.get('next', '')

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            return HttpResponseRedirect(reverse('mainapp:index'))

    context = {
        'login_form': login_form,
        'next_param': next_param,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('mainapp:index'))


def register(request):
    """
    TODO: сделать отделную страницу после регистрации
    """
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            new_user = register_form.save()
            send_verify_email(new_user)
            return HttpResponseRedirect(reverse('authapp:login'))
    else:
        register_form = ShopUserRegisterForm()
    context = {
        'register_form': register_form,
    }
    return render(request, 'authapp/register.html', context)


def edit(request):
    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        edit_profile_form = ShopUserProfileEditForm(request.POST, instance=request.user.shopuserprofile)

        if edit_form.is_valid() and edit_profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('mainapp:index'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)
        edit_profile_form = ShopUserProfileEditForm(request.POST, instance=request.user.shopuserprofile)

    context = {
        'edit_form': edit_form,
        'edit_profile_form': edit_profile_form,
    }
    return render(request, 'authapp/edit.html', context)


def verify(request, email, key):
    user = ShopUser.objects.get(email=email)
    if user:
        print(user.activate_key)
        if user.activate_key == key and not user.is_activate_key_expired():
            user.activate_user()
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
    return render(request, 'authapp/register_result.html')

mysite/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/style.css' %}">
    <link rel="stylesheet" href="/static/mainapp/fonts/font-awesome/css/font-awesome.css">


    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>

	<div class="container">
        <div class="login p-2 bg-light border">
            <div class="h2 text-center head">
                {% block head %}
                Вход в систему
                {% endblock %}
            </div>

            {% block content %}

            {% endblock %}
        </div>
	</div>
</body>
</html>

mysite/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block head %}
    Редактирование
{% endblock %}
{% block content %}
{% if user.avatar %}
    <img src = "{{ user.avatar.url }}">
{% endif %}
    <form class="form-horizontal " action="{% url 'authapp:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        {{ edit_profile_form.as_p }}
        <input type="submit" class="btn btn-primary" value="Сохранить">
    </form>
    <hr>
    <a href="{% url 'mainapp:index' %}">На главную</a>

{% endblock %}

mysite/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <div class="" style="padding: 20px">
    <form class="form-horizontal " action="{% url 'authapp:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        {% if next_param %}
            <input type="hidden" name="next" value="{{ next_param }}">
        {% endif %}
        <input type="submit" class="btn btn-primary" value="Войти">
    </form>
        <hr>
        <a class="btn btn-link" href="{% url 'authapp:register' %}">Зарегистрироваться</a>
        <a class="btn btn-link" href="{% url 'mainapp:index' %}">На главную</a>
        <a class="btn btn-link" href="{% url 'social:begin' 'google-oauth2' %}">Google</a>


    </div>
{% endblock %}

mysite/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block head %}
    Регистрация
{% endblock %}
{% block content %}
    <form class="form-horizontal " action="{% url 'authapp:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <input type="submit" class="btn btn-primary" value="Зарегистрироваться">
    </form>
        <hr>
        <a href="{% url 'authapp:login' %}">Войти</a>
        <a class="btn btn-link" href="{% url 'mainapp:index' %}">На главную</a><br>

{% endblock %}

mysite/authapp/templates/authapp/register_result.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
        {% if user.is_authenticated %}
            <h1>Поздравляем!</h1>
            <h2>Добро пожаловать в наш магазин!</h2>
        {% else %}
            <h1>Ошибка</h1>
            <h2>Что-то пошло не так :(</h2>
            <p>Обратитесь в поддержку по адрессу support@gb.local</p>
        {% endif %}
        <hr>
        <a href="{% url 'mainapp:index' %}">На главную</a>

{% endblock %}